[package]
name = "droolmaw"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dirs = "5.0.1"
serde = "1.0.213"
serde_derive = "1.0.213"
toml = "0.8.19"
